PPR = 0x00
ANGLE_QUANT = 0x01
ENABLE = 0x03
SPEED = 0x04
ANGLE = 0x05
MODE = 0x07
COMMAND = 0x08
ANGLE_FROM_BOOT = 0x09
RESET_ANGLE_FROM_BOOT = 0x0B
ERROR = 0x0C
STATE = 0x0D

offsets_list = [PPR, ANGLE_QUANT, ENABLE, SPEED, ANGLE, MODE,COMMAND, ANGLE_FROM_BOOT, RESET_ANGLE_FROM_BOOT, ERROR, STATE]
