FULL = 200
HALF = FULL*2
QUATER = HALF*2
ONETOEIGHT = QUATER*2
ONETOSEXTEEN = ONETOEIGHT*2
ONETOTHIRTYTWO = ONETOSEXTEEN*2
ONETOSIXTYFOUR = ONETOTHIRTYTWO*2
ONETOHUNDREDTWENTYEIGHT = ONETOSIXTYFOUR*2
ONETOTWOHUNDERFIFTYSIX = ONETOHUNDREDTWENTYEIGHT*2

PPR_values_list = [FULL, HALF, QUATER, ONETOEIGHT, ONETOSEXTEEN, ONETOTHIRTYTWO, ONETOSIXTYFOUR, ONETOHUNDREDTWENTYEIGHT, ONETOTWOHUNDERFIFTYSIX]
